name: dijital_gunluk_ai
description: Cihaz-içi AI destekli dijital günlük (şifreli DB + biyometrik)
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  local_auth: ^2.3.0
  flutter_secure_storage: ^9.2.2
  sqflite_sqlcipher: ^2.3.3
  path: ^1.9.0
  pdf: ^3.11.1
  file_picker: ^8.1.2
  provider: ^6.1.2
  intl: ^0.19.0
  tflite_flutter: ^0.10.4

flutter:
  uses-material-design: true
  assets:
    - assets/tflite/model.tflite
